# Generated by Django 4.1.7 on 2024-08-30 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drf_api_logger", "0002_auto_20211221_2155"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APILogsModel",
        ),
    ]
